services:
  backend:
    image: swoyammagar/dockerapp-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: ${MONGO_URI}
    networks:
      - mern-network

  frontend:
    image: swoyammagar/dockerapp-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network: