services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongovol:/data/db
    networks:
      - mern-network

  backend:
    image: swoyammagar/dockerapp-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/mern-movie-watchlist
    networks:
      - mern-network

  frontend:
    image: swoyammagar/dockerapp-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-network

volumes:
  mongovol:

networks:
  mern-network: